# Generated by Django 5.1.6 on 2025-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('REVIEWED', 'Рассмотрена'), ('ACCEPTED', 'Принята'), ('REJECTED', 'Отклонена')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'Информационные технологии'), ('SALES', 'Продажи'), ('MARKETING', 'Маркетинг'), ('FINANCE', 'Финансы'), ('HR', 'Кадры'), ('OTHER', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY', 'Стартовая'), ('JUNIOR', 'Юниор'), ('MID', 'Средний'), ('SENIOR', 'Сеньор'), ('LEAD', 'Лид')], default='ENTRY', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Удаленно', max_length=100),
        ),
    ]
